### ISSUE TITLE
Add more description for request/response of CaseTest entities

### ISSUE THREAD

**Issue by dkhmelenko** [art-divin/mester-rest-api#10]
Please more description for each field in request/response of `CaseTest` entities.
For example, which kind of values can have the field `status` except `default`? And what does the status `default` mean?

**Comment by art-divin** [comment]
For now, currently there are 3 statuses:
    case Default = "default"
    case Failed = "failed"
    case Succeed = "passed"

each of which represents status of the `Test` / `CaseTest` / `StepTest`.
`default` is a default status which represents default status of the object. This status means that no actions were performed on current object. 
`failed` and `passed` statuses show current status of the object. 
Object is `failed` when any of its children is failed, if there are no children then object has `failed` status only in case when its status field value was set to `failed`.
The same rule applies for `passed`.

I'll update documentation later on, for now I'll leave this issue as opened.

**Comment by art-divin** [comment]
[This specification](https://github.com/art-divin/mester-rest-api/wiki/Domain-JSON#post-testidsubmit) represents how one should POST CaseTest entities with status updates
