### ISSUE TITLE
Wrong format POST /step

### ISSUE THREAD

**Issue by dkhmelenko** [art-divin/mester-rest-api#7]
According to the current format in the request `POST /step`, step `number` should be integer and `testCaseId` should be integer too. But actually `testCaseId` is String and api call works if `testCaseId` is String. Documentation should be updated.

Also, as a suggestion, would be nice to wrap `number` as a String. There should be always only integer data, but it would be better to have something like `"number":"5"`, not `"number":5`

What do you think about such improvement?

**Comment by art-divin** [comment]
> Documentation should be updated.

Done!

> Also, as a suggestion, would be nice to wrap number as a String. There should be always only integer data, but it would be better to have something like "number":"5", not "number":5

I am not sure why sequence number should be a string, since it represents sorting order of the step. I think it would be better to leave it as a number
